S0 crud consultant
WildCodeSchool/202302-orleans-php-project-externatic pull request #10
Opened 2023-06-11 17:52 UTC by mathysfrc

2023-06-11 18:23 UTC, jaalazard approved these changes

2023-06-12 07:33 UTC, PAimery approved these changes

2023-06-12 08:33 UTC, sblondeau requested changes
Tu m'as fais TOUT le CRUD d'un coup !!! j'ai pourtant bien insisté et vous ai montré en LC que ça doit être découpé !
A revoir désolé

2023-06-12 08:33 UTC, sblondeau commented on src/Controller/ConsultantController.php
> +            'consultants' => $consultantRepository->findAll(),
order by name

2023-06-12 08:33 UTC, sblondeau commented on src/DataFixtures/ConsultantFixtures.php
> +        $consultant = new Consultant();
c'est bien que tu fasses un consultant donc tu maitrise les données

mais en dessous ajoute une boucle ou tu ajoutes une 10aine d'autres consultatnt pour remplir un peu la bdd

2023-06-13 06:59 UTC, closed without merging