Fix nav
WildCodeSchool/202302-orleans-php-project-externatic pull request #106
Opened 2023-07-03 14:59 UTC by Cardamced

2023-07-03 14:59 UTC, jaalazard submitted a review, later dismissed

2023-07-03 15:03 UTC, mathysfrc submitted a review, later dismissed

2023-07-03 15:09 UTC, Zakari-B requested changes

2023-07-03 15:09 UTC, Zakari-B commented on src/Controller/CandidateController.php
> +    public function show(): Response
Je suis extrêmement surpris que vous me proposiez une route show avec aucun identifiant pour le candidat qu'on doit show !

(Quid du cas ou je veux afficher un profil qui n'est PAS celui de l'utilisateur connecté ?)

2023-07-04 14:48 UTC, PAimery submitted a review, later dismissed

2023-07-04 15:10 UTC, sblondeau approved these changes

2023-07-04 15:25 UTC, merged