Fix skill supp
WildCodeSchool/202302-orleans-php-project-externatic pull request #107
Opened 2023-07-03 15:01 UTC by jaalazard

2023-07-03 15:02 UTC, Cardamced submitted a review, later dismissed

2023-07-03 15:03 UTC, mathysfrc submitted a review, later dismissed

2023-07-03 15:12 UTC, Zakari-B requested changes

2023-07-03 15:12 UTC, Zakari-B commented on templates/candidate/show.html.twig
> +						<a class="text-light fw-bold text-decoration-none" href="{{ path('app_candidate_add_experience', {'id': candidate.id}) }}">Ajouter une expérience</a>
Pas de 'a' dans les 'button' !!

2023-07-03 15:12 UTC, Zakari-B commented on templates/candidate/show.html.twig
> +						<a class="text-light fw-bold text-decoration-none" href="{{ path('app_candidate_add_skill', {'id': candidate.id}) }}">Ajouter une compétence</a>
idem

2023-07-03 21:21 UTC, mathysfrc approved these changes

2023-07-04 13:28 UTC, PAimery submitted a review, later dismissed

2023-07-04 14:46 UTC, PAimery approved these changes

2023-07-04 15:09 UTC, sblondeau approved these changes

2023-07-04 15:09 UTC, merged