S0 consultant crud
WildCodeSchool/202302-orleans-php-project-externatic pull request #11
Opened 2023-06-12 10:34 UTC by mathysfrc

2023-06-12 10:39 UTC, jaalazard approved these changes

2023-06-12 12:03 UTC, Cardamced submitted a review, later dismissed

2023-06-12 13:48 UTC, jaalazard submitted a review, later dismissed

2023-06-12 15:30 UTC, sblondeau requested changes

2023-06-12 15:30 UTC, sblondeau commented on src/Controller/ConsultantController.php
> +            'consultant' => $consultantRepository->findAll(),
order by name

2023-06-12 15:30 UTC, sblondeau commented on src/DataFixtures/ConsultantFixtures.php
> +
créé plusieurs consultants, un seul c'est un peu juste
tu peux en garder un comme ça dont tu maitrise les données, et en dessous tu en génère 10 de plus en faker

2023-06-12 15:30 UTC, sblondeau commented on templates/consultant/index.html.twig
> +                    <th class="text-dark fw-400 text-uppercase fs-5 mx-md-5 mx-0 my-5">Id</th>
id pas utile de garder cette colonne

2023-06-12 15:30 UTC, sblondeau commented on templates/consultant/index.html.twig
> +                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewbox="0 0 16 16">
utilie un include pour tes svg, surtout celui là tu vas t'en resservir plein de fois

2023-06-12 15:30 UTC, sblondeau commented on templates/consultant/index.html.twig
> +            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewbox="0 0 16 16">
idem

2023-06-13 06:05 UTC, sblondeau approved these changes

2023-06-13 06:05 UTC, merged