S04 #41 ad/cons list job offer
WildCodeSchool/202302-orleans-php-project-externatic pull request #110
Opened 2023-07-04 14:45 UTC by PAimery

2023-07-04 15:20 UTC, jaalazard approved these changes

2023-07-04 17:05 UTC, mathysfrc submitted a review, later dismissed

2023-07-05 08:04 UTC, sblondeau requested changes

2023-07-05 08:04 UTC, sblondeau commented on templates/admin_consultant/index.html.twig
> +					</div>
la card peut etre mis dans un include pour simplifier la lecture du code et la rendre éventuellement réutilisable ailleurs

2023-07-05 13:14 UTC, mathysfrc submitted a review, later dismissed

2023-07-05 13:15 UTC, jaalazard submitted a review, later dismissed

2023-07-06 08:07 UTC, jaalazard approved these changes

2023-07-06 08:12 UTC, mathysfrc submitted a review, later dismissed

2023-07-06 08:12 UTC, Cardamced submitted a review, later dismissed

2023-07-06 09:57 UTC, Zakari-B requested changes
git rm --cached

2023-07-06 09:57 UTC, Zakari-B commented on templates/components/admin/nav-admin.html.twig
La navbar admin ne devrait pas être dans une US sur les job offer

2023-07-06 09:57 UTC, Zakari-B commented on templates/components/_navbar.html.twig
Pourquoi modifier le composant navbar ici ? Ce n'est pas de cette US.

2023-07-06 09:57 UTC, Zakari-B commented on templates/company/home/index.html.twig
Ce fichier ne devrait pas être dans cette US.

2023-07-06 09:57 UTC, Zakari-B commented on src/Repository/JobOfferRepository.php
A retirer de la PR. Je ne sais pas quelle extension tu utilises qui formate comme ça mais je recommande fortement de la retirer.

2023-07-06 09:57 UTC, Zakari-B commented on src/Controller/PageCandidateController.php
Ce fichier est il en lien avec cette US?

2023-07-06 09:57 UTC, Zakari-B commented on assets/styles/app.scss
A retirer de la PR.

2023-07-06 09:57 UTC, Zakari-B commented on src/DataFixtures/JobOfferFixtures.php
> +            'job' => 'Data analyst', 'entreprise' => 'Wild code school', 'contract' => 'Alternance', 'city' => 'Nantes',
Tu mets Wild code school partout alors que la description indique autre chose, si ta fixture n'est pas aléatoire par faker, autant que tes infos soient cohérentes quand même

2023-07-06 10:02 UTC, Zakari-B commented on src/Controller/AdminConsultantController.php
> +            'selectedJobOffer' => $selectedJobOffer,
C'est moi qui voulait selectedJobOffer pour éviter toute confusion possible avec la boucle for jobOffers as jobOffer

2023-07-06 10:02 UTC, Zakari-B commented on templates/admin_consultant/index.html.twig
> +					</div>
Cette demande n'a pas été traitée.

2023-07-06 10:26 UTC, Cardamced approved these changes

2023-07-06 11:47 UTC, jaalazard approved these changes

2023-07-06 13:06 UTC, closed without merging