navbar admin
WildCodeSchool/202302-orleans-php-project-externatic pull request #12
Opened 2023-06-12 14:05 UTC by mathysfrc

2023-06-12 14:32 UTC, jaalazard approved these changes

2023-06-12 14:43 UTC, Cardamced submitted a review, later dismissed

2023-06-12 15:32 UTC, sblondeau requested changes

2023-06-12 15:32 UTC, sblondeau commented on templates/components/admin/_navbar-admin.html.twig
> +					<a class="nav-link mx-3" href="#">JOB FAMILY</a>
english ?

2023-06-13 06:47 UTC, sblondeau approved these changes

2023-06-13 06:47 UTC, merged