user provider
WildCodeSchool/202302-orleans-php-project-externatic pull request #13
Opened 2023-06-12 14:31 UTC by jaalazard

2023-06-12 14:34 UTC, mathysfrc submitted a review, later dismissed

2023-06-12 14:58 UTC, rubenk3 submitted a review, later dismissed

2023-06-12 15:10 UTC, rubenk3 approved these changes

2023-06-13 06:57 UTC, sblondeau requested changes
ce n'est pas une user story !
a minima, il faut ajouter des fixtures et afficher les users qq part, que ça corresponde à une fonctionnalité; là c'est une tache de US.
Je ferais tout le login (en suivant les étapes de la doc) dans l'US

2023-06-14 09:38 UTC, mathysfrc approved these changes

2023-06-14 09:46 UTC, closed without merging