S02 connexion
WildCodeSchool/202302-orleans-php-project-externatic pull request #16
Opened 2023-06-12 17:06 UTC by jaalazard

2023-06-12 17:43 UTC, mathysfrc submitted a review, later dismissed

2023-06-12 18:21 UTC, mathysfrc submitted a review, later dismissed

2023-06-13 07:01 UTC, sblondeau requested changes
il manque aussi des fixtures

2023-06-13 07:01 UTC, sblondeau commented on src/Entity/User.php
> +    #[ORM\Column(length: 180, unique: true)]
manque les asserts (Assert\Email, Length, NotBlank...)

2023-06-13 07:01 UTC, sblondeau commented on templates/login/index.html.twig
> +    <form action="{{ path('app_login') }}" method="post">
le style est pas fait là ? non ?

2023-06-14 09:28 UTC, mathysfrc submitted a review, later dismissed

2023-06-14 09:39 UTC, PAimery approved these changes

2023-06-14 09:47 UTC, rubenk3 approved these changes

2023-06-14 09:47 UTC, PAimery approved these changes

2023-06-14 09:48 UTC, Cardamced approved these changes

2023-06-14 10:25 UTC, merged