initialisation
WildCodeSchool/202302-orleans-php-project-externatic pull request #2
Opened 2023-06-05 16:45 UTC by jaalazard

PR d'Initialisation

2023-06-05 17:00 UTC, mathysfrc submitted a review, later dismissed

2023-06-05 17:23 UTC, Cardamced submitted a review, later dismissed

2023-06-05 18:52 UTC, sblondeau requested changes

2023-06-05 18:52 UTC, sblondeau commented on assets/styles/variables.scss
> +}
inutile, déjà dans bootstrap

2023-06-05 18:52 UTC, sblondeau commented on assets/styles/variables.scss
> +}
je pense que le primary devrait etre le violet d'externatic non ? 
et en background-color plutot le $dark ?

2023-06-05 18:52 UTC, sblondeau commented on assets/styles/variables.scss
> +$secondary: #CA2061;
en primary plutot

2023-06-05 18:52 UTC, sblondeau commented on templates/home/index.html.twig
> +        <h1 class="text-secondary">
et du coup un text-primary ;-)

2023-06-06 07:32 UTC, sblondeau approved these changes

2023-06-06 07:32 UTC, merged