Style.profil.ja
WildCodeSchool/202302-orleans-php-project-externatic pull request #238
Opened 2023-07-25 15:19 UTC by mathysfrc

2023-07-25 15:19 UTC, jaalazard approved these changes

2023-07-25 15:19 UTC, PAimery submitted a review, later dismissed

2023-07-25 15:20 UTC, Cardamced submitted a review, later dismissed

2023-07-25 21:16 UTC, sblondeau requested changes

2023-07-25 21:16 UTC, sblondeau commented on templates/candidate/profile.html.twig
> +					<span href="{{ vich_uploader_asset(app.user.candidate, 'cvitaeFile') }}">Mon CV</span>
tjs pas corrigé

2023-07-26 07:26 UTC, PAimery approved these changes

2023-07-26 07:26 UTC, jaalazard approved these changes

2023-07-26 07:51 UTC, sblondeau approved these changes

2023-07-26 07:51 UTC, merged