Form candidate
WildCodeSchool/202302-orleans-php-project-externatic pull request #25
Opened 2023-06-14 14:33 UTC by Cardamced

2023-06-14 14:33 UTC, jaalazard approved these changes

2023-06-14 14:33 UTC, PAimery submitted a review, later dismissed

2023-06-14 14:41 UTC, sblondeau requested changes
en l'état, ta PR n'a pas de vue, donc ne correspond pas à ton US !

2023-06-14 14:41 UTC, sblondeau commented on migrations/Version20230614133213.php
NON ! tu as du faire un make:migraiton avant de faire un d:m:m

2023-06-15 09:03 UTC, jaalazard submitted a review, later dismissed

2023-06-15 09:35 UTC, PAimery approved these changes

2023-06-15 10:02 UTC, Zakari-B requested changes

2023-06-15 10:02 UTC, Zakari-B commented on templates/Candidate/show.html.twig
> +{% block footer %}{% endblock %}
S'il est prévu de rajouter plus tard un footer dans le base.html.twig, ce bloc est à retirer (sauf si le candidat ne doit pas avoir de footer, pour X raison)

2023-06-15 10:02 UTC, Zakari-B commented on src/Form/RegistrationFormType.php
Le fichier Form a été effacé alors que l'US s'appelle "FORM candidate" ? Je crois qu'il y a un souci.

2023-06-15 10:11 UTC, jaalazard approved these changes

2023-06-15 12:14 UTC, Zakari-B commented
Qu'n est il de ma question ? La branche s'appelle FormCandidate et il y a tout sauf un form dans cette PR.

2023-06-15 12:15 UTC, merged