page list des offres d'emlpoi
WildCodeSchool/202302-orleans-php-project-externatic pull request #43
Opened 2023-06-15 14:40 UTC by PAimery

2023-06-15 14:40 UTC, jaalazard approved these changes

2023-06-15 14:40 UTC, mathysfrc submitted a review, later dismissed

2023-06-15 21:42 UTC, sblondeau requested changes

2023-06-15 21:42 UTC, sblondeau commented on templates/admin_jobOffer/index.html.twig
> +						<td colspan="7">no records found</td>
traduction

2023-06-15 21:42 UTC, sblondeau commented on templates/admin_jobOffer/index.html.twig
> +								<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-eye-fill" viewbox="0 0 16 16">
svg en include, ça sera plus lisible

2023-06-16 14:46 UTC, mathysfrc approved these changes

2023-06-16 14:46 UTC, jaalazard approved these changes

2023-06-19 06:48 UTC, sblondeau approved these changes

2023-06-19 06:48 UTC, merged