homepage company
WildCodeSchool/202302-orleans-php-project-externatic pull request #45
Opened 2023-06-15 14:57 UTC by mathysfrc

2023-06-15 14:59 UTC, jaalazard submitted a review, later dismissed

2023-06-15 14:59 UTC, PAimery submitted a review, later dismissed

2023-06-15 21:45 UTC, sblondeau requested changes

2023-06-15 21:45 UTC, sblondeau commented on templates/home/index.html.twig
> +			<div class="col">
si tu mets col, tu auras autant de colonnes que d'entreprise, si tu as 100 entreprises ça va etre embetant...
soit tu limit le nombre de company récupérées, soit tu utilises qq chose comm col-6 col-sm-4 col-md-3 col-lg-2 et ça retournera à la ligne une fois arrivé à 12 colonnes. Mais si tu as beaucoup d'entreprises ça va faire un gros paquet

2023-06-16 14:45 UTC, jaalazard approved these changes

2023-06-16 14:45 UTC, PAimery approved these changes

2023-06-19 06:49 UTC, sblondeau approved these changes

2023-06-19 06:49 UTC, merged