Business card
WildCodeSchool/202302-orleans-php-project-externatic pull request #52
Opened 2023-06-18 16:30 UTC by mathysfrc

2023-06-18 17:17 UTC, jaalazard submitted a review, later dismissed

2023-06-18 17:54 UTC, Cardamced submitted a review, later dismissed

2023-06-19 09:22 UTC, sblondeau requested changes
images trop grosses ! ça devrait pas passer la review ça ;-) 
a redécouper comme expliqué

2023-06-19 11:58 UTC, jaalazard approved these changes

2023-06-19 12:00 UTC, jaalazard submitted a review, later dismissed

2023-06-19 12:00 UTC, PAimery submitted a review, later dismissed

2023-06-19 12:00 UTC, jaalazard submitted a review, later dismissed

2023-06-19 14:36 UTC, sblondeau requested changes

2023-06-19 14:36 UTC, sblondeau commented on assets/images/technology.jpg
tjs trop grosse !!

2023-06-19 14:36 UTC, sblondeau commented on src/Controller/BusinessCardController.php
> +            'business_cards' => $businessRepository->findAll(),
order by name ?

2023-06-19 14:36 UTC, sblondeau commented on templates/business-card/index.html.twig
> +				<div class="col-md-8 my-md-5 px-0">
pas de margin/padding en x sur les row /col

2023-06-19 14:36 UTC, sblondeau commented on templates/business-card/index.html.twig
> +					<div class="d-grid">
pourquoi un d-grid ? j'ai l'impression que tu te facilite pas la vie :D

2023-06-20 07:11 UTC, jaalazard submitted a review, later dismissed

2023-06-20 07:11 UTC, PAimery submitted a review, later dismissed

2023-06-20 07:17 UTC, sblondeau requested changes

2023-06-20 07:17 UTC, sblondeau commented on src/Controller/BusinessCardController.php
> +}
toute cette partie qui reste du CRUD est à enlever, tu le regénéreras avec un AdminBusinessCardContorller

2023-06-20 07:17 UTC, sblondeau commented on src/Form/BusinessCardType.php
> +}
idem fichier à supprimer pour le moment, en fait tu as virer que les vues du crud et pas le reste

2023-06-20 10:09 UTC, jaalazard approved these changes

2023-06-20 10:09 UTC, PAimery approved these changes

2023-06-20 11:33 UTC, sblondeau approved these changes

2023-06-20 11:33 UTC, merged