page candidate avec statistiques - info -FAQ
WildCodeSchool/202302-orleans-php-project-externatic pull request #62
Opened 2023-06-22 08:08 UTC by PAimery

2023-06-22 08:10 UTC, jaalazard submitted a review, later dismissed

2023-06-22 09:55 UTC, Cardamced approved these changes

2023-06-22 09:56 UTC, jaalazard approved these changes

2023-06-22 11:38 UTC, sblondeau requested changes
- images trop grosses
- nom d'images plus simples
-

2023-06-22 11:38 UTC, sblondeau commented on assets/images/campaign-creators-gMsnXqILjp4-unsplash.jpg
trop gros
a renommer avec un nom simplifié

2023-06-22 11:38 UTC, sblondeau commented on templates/PageCandidate/index.html.twig
> +					<div class="col-md-8 col-12 my-md-5 my-0">
pas de col-12 ça sert à rien c'est déjà la taille par défaut

2023-06-22 11:38 UTC, sblondeau commented on templates/PageCandidate/index.html.twig
> +										<br>Vous recherchez un sponsor pour votre événement ? N’hésitez pas à nous solliciter ici.
ul / li pour afficher des listes

2023-06-22 14:05 UTC, mathysfrc approved these changes

2023-06-22 14:06 UTC, jaalazard approved these changes

2023-06-22 14:39 UTC, jaalazard submitted a review, later dismissed

2023-06-22 14:40 UTC, mathysfrc submitted a review, later dismissed

2023-06-22 15:22 UTC, jaalazard submitted a review, later dismissed

2023-06-22 20:59 UTC, mathysfrc approved these changes

2023-06-22 20:59 UTC, sblondeau requested changes
les images sont trop grosses !

2023-06-23 07:37 UTC, jaalazard submitted a review, later dismissed

2023-06-23 07:39 UTC, mathysfrc submitted a review, later dismissed

2023-06-23 08:06 UTC, sblondeau commented
image ~ 100Ko

2023-06-23 09:17 UTC, mathysfrc submitted a review, later dismissed

2023-06-23 09:21 UTC, jaalazard submitted a review, later dismissed

2023-06-23 09:22 UTC, sblondeau submitted a review, later dismissed

2023-06-23 09:28 UTC, jaalazard approved these changes

2023-06-23 09:36 UTC, merged