Upload s3 us9
WildCodeSchool/202302-orleans-php-project-externatic pull request #76
Opened 2023-06-23 08:14 UTC by Cardamced

2023-06-23 09:36 UTC, jaalazard approved these changes

2023-06-23 09:40 UTC, sblondeau requested changes

2023-06-23 09:40 UTC, sblondeau commented on migrations/Version20230622155231.php
> +
cette migration me semble pas bonne

2023-06-23 09:40 UTC, sblondeau commented on templates/home/index.html.twig
> +				<h2 class="h3 text-dark fw-400 fs-2 text-uppercase  mx-md-5 mx-0 my-5">Les cabinets de recrutement se limitent souvent au cvitae.<br>
cv ici

2023-06-23 13:19 UTC, PAimery approved these changes

2023-06-25 14:05 UTC, sblondeau approved these changes

2023-06-25 14:05 UTC, merged