dropdown
WildCodeSchool/202302-orleans-php-project-externatic pull request #79
Opened 2023-06-23 14:39 UTC by mathysfrc

2023-06-23 14:41 UTC, jaalazard submitted a review, later dismissed

2023-06-23 18:35 UTC, Cardamced submitted a review, later dismissed

2023-06-25 14:08 UTC, sblondeau requested changes

2023-06-25 14:08 UTC, sblondeau commented on templates/components/_navbar.html.twig
> +					{% endif %}
les `<li class="nav-item my-3">` peuvent etre à l'extérieux de if/else et tu ne chanque que la ligne du lien

2023-06-25 14:08 UTC, sblondeau commented on templates/components/_navbar.html.twig
>  				<li class="nav-item">
MÉTIERS (accent majuscule)

2023-06-26 08:07 UTC, jaalazard approved these changes

2023-06-26 09:53 UTC, PAimery approved these changes

2023-06-26 10:24 UTC, sblondeau approved these changes

2023-06-26 10:24 UTC, merged