S0 page accueil
WildCodeSchool/202302-orleans-php-project-externatic pull request #8
Opened 2023-06-08 13:21 UTC by mathysfrc

2023-06-08 14:43 UTC, Cardamced submitted a review, later dismissed

2023-06-08 14:54 UTC, jaalazard submitted a review, later dismissed

2023-06-08 15:16 UTC, Zakari-B requested changes

2023-06-08 15:16 UTC, Zakari-B commented on templates/home/index.html.twig
> +				<button type="button" class="btn btn-primary btn-lg fw-bold text-uppercase mx-md-5 mx-0 mb-5 rounded-0">candidat</button>
Majuscule.

2023-06-08 15:16 UTC, Zakari-B commented on templates/home/index.html.twig
> +				<button type="button" class="btn btn-primary btn-lg fw-bold text-uppercase mx-md-5 mx-0 mb-5 rounded-0">nos offres</button>
Idem

2023-06-08 15:20 UTC, jaalazard approved these changes

2023-06-08 15:20 UTC, Cardamced approved these changes

2023-06-08 20:59 UTC, sblondeau requested changes

2023-06-08 20:59 UTC, sblondeau commented on assets/styles/app.scss
> +@import '_home';
si c'est du style propre à la home page, tu ne dois pas l'import dans app sinon il sera sur toutes les pages
il faut créer un fichier home.css séparé via un addStyleEntry dans le webpack.config

2023-06-08 20:59 UTC, sblondeau commented on templates/home/index.html.twig
> +			<button type="button" class="btn btn-primary btn-lg fw-bold text-uppercase mb-5 px-md-5 px-3 rounded-0">Candidat</button>
non si tu mets des button ça ne sera pas cliquable ! tu veux des liens non ?

2023-06-08 20:59 UTC, sblondeau commented on templates/home/index.html.twig
> +		</div>
un div fermant de trop non ? et ça me semble mal indenté

2023-06-08 21:08 UTC, mathysfrc commented on assets/styles/app.scss
> +@import '_home';
je ne comprends pas comment faire ?

2023-06-09 08:21 UTC, jaalazard approved these changes

2023-06-09 08:22 UTC, PAimery approved these changes

2023-06-09 09:05 UTC, sblondeau approved these changes

2023-06-09 09:05 UTC, merged