Registration Form
WildCodeSchool/202302-orleans-php-project-externatic pull request #81
Opened 2023-06-26 11:10 UTC by Cardamced

2023-06-26 12:02 UTC, mathysfrc submitted a review, later dismissed

2023-06-26 12:02 UTC, jaalazard submitted a review, later dismissed

2023-06-26 13:31 UTC, Zakari-B requested changes

2023-06-26 13:31 UTC, Zakari-B commented on templates/security/index.html.twig
Ce fichier ne devrait pas être la.

2023-06-26 14:51 UTC, mathysfrc submitted a review, later dismissed

2023-06-26 14:58 UTC, jaalazard approved these changes

2023-06-26 15:06 UTC, PAimery approved these changes

2023-06-26 20:59 UTC, mathysfrc submitted a review, later dismissed

2023-06-27 08:42 UTC, PAimery approved these changes

2023-06-27 12:22 UTC, jaalazard approved these changes

2023-06-27 13:39 UTC, sblondeau requested changes

2023-06-27 13:39 UTC, sblondeau commented on migrations/Version20230626151330.php
> +    }
devrait pas etre là ? déjà créé par les collègue non ? vous me l'avez tous créé celle-là :D

2023-06-27 13:49 UTC, jaalazard approved these changes

2023-06-27 13:49 UTC, mathysfrc approved these changes

2023-06-27 13:50 UTC, mathysfrc approved these changes

2023-06-27 21:38 UTC, sblondeau approved these changes

2023-06-27 21:38 UTC, merged