barre de recherche job
WildCodeSchool/202302-orleans-php-project-externatic pull request #82
Opened 2023-06-26 12:58 UTC by mathysfrc

2023-06-26 13:03 UTC, jaalazard submitted a review, later dismissed

2023-06-26 14:40 UTC, Cardamced approved these changes

2023-06-27 06:58 UTC, sblondeau requested changes

2023-06-27 06:58 UTC, sblondeau commented on src/Controller/JobOfferController.php
> +            $city = $form->getData()['city'] ? $form->getData()['city']->getCity() : '';
$city = $form->getData()['city'] ?? ''

2023-06-27 06:58 UTC, sblondeau commented on assets/styles/jobOffer.scss
> +
media query utile ? 
ne pas utiliser d'id (#) pour styliser

2023-06-27 06:58 UTC, sblondeau commented on src/Form/SearchJobType.php
> +                },
je ne pense pas que ce soit la bonne approche, on en discute

2023-06-27 10:22 UTC, PAimery approved these changes

2023-06-27 10:23 UTC, jaalazard approved these changes

2023-06-27 13:50 UTC, sblondeau requested changes

2023-06-27 13:50 UTC, sblondeau commented on src/Form/SearchJobType.php
> +        $builder
- setMethod('GET')
- getBlockPrefix() pour renommer le form
- csrf_protection => false

2023-06-27 14:08 UTC, jaalazard approved these changes

2023-06-27 14:08 UTC, PAimery approved these changes

2023-06-27 21:40 UTC, sblondeau requested changes

2023-06-27 21:40 UTC, sblondeau commented on src/Controller/JobOfferController.php
> +            }
non pas de n/a c'est pas propre de mettre ça en dur ! 
Ca ce gère coté entityType éventuellement

2023-07-02 15:24 UTC, jaalazard approved these changes

2023-07-03 07:09 UTC, PAimery submitted a review, later dismissed

2023-07-03 08:17 UTC, jaalazard submitted a review, later dismissed

2023-07-03 08:39 UTC, PAimery submitted a review, later dismissed

2023-07-03 14:23 UTC, jaalazard approved these changes

2023-07-03 14:23 UTC, PAimery submitted a review, later dismissed

2023-07-03 15:21 UTC, sblondeau submitted a review, later dismissed

2023-07-04 07:46 UTC, merged